### ISSUE TITLE
Sync exception

### ISSUE THREAD

**Issue by aleksey-zhidkov** [aleksey-zhidkov/jeb-k#1]
Exception in thread "main" java.lang.IllegalArgumentException: Directory is needed
	at kotlin.io.FileTreeWalk$DirectoryState.<init>(FileTreeWalk.kt:52)
	at kotlin.io.FileTreeWalk$BottomUpDirectoryState.<init>(FileTreeWalk.kt:60)
	at kotlin.io.FileTreeWalk.pushState(FileTreeWalk.kt:151)
	at kotlin.io.FileTreeWalk.gotoNext(FileTreeWalk.kt:183)
	at kotlin.io.FileTreeWalk.access$gotoNext(FileTreeWalk.kt:39)
	at kotlin.io.FileTreeWalk$it$1.hasNext(FileTreeWalk.kt:249)
	at kotlin.io.FilesKt__UtilsKt.deleteRecursively(Utils.kt:465)
	at kotlin.io.FilesKt.deleteRecursively(Unknown Source)
	at jeb.Io.remove(Io.kt:23)
	at jeb.Backuper.prepareTape(Backuper.kt:59)
	at jeb.Backuper.doBackup(Backuper.kt:37)
	at jeb.JebKt.backup(jeb.kt:33)
	at jeb.JebKt.main(jeb.kt:12)

**Comment by aleksey-zhidkov** [comment]
Not a bug
