### ISSUE TITLE
NPE when backupsDir does not exists

### ISSUE THREAD

**Issue by aleksey-zhidkov** [aleksey-zhidkov/jeb-k#11]
```
Exception in thread "main" java.lang.NullPointerException
	at jeb.Storage.fileExists(Storage.kt:111)
	at jeb.Backuper.doBackup(Backuper.kt:16)
	at jeb.JebKt.doBackup(jeb.kt:55)
	at jeb.JebKt.backup(jeb.kt:42)
	at jeb.JebKt.main(jeb.kt:16)
```

**Comment by aleksey-zhidkov** [comment]
Could not reproduce
